### ISSUE TITLE
Support "reason" when dead-lettering

### ISSUE THREAD

**Issue by bergie** [msgflo/msgflo#11]
When messages are `nack`ed in order to dead-letter them, it would be useful to provide a "reason" together with the rejection (for example, `message` of `Error` objects sent to NoFlo error ports).

From [RabbitMQ DLX docs](https://www.rabbitmq.com/dlx.html):

> The dead-lettering process adds an array to the header of each dead-lettered message named x-death. This array contains an entry for each dead lettering event, identified by a pair of {queue, reason}.

**Comment by bergie** [comment]
Hmm... it seems `reason` is a enum. But maybe we can add headers?

**Comment by jonnor** [comment]
Haven't actually needed this. If anyone else wants it, issue should be opened in [msgflo-nodejs](https://github.com/msgflo/msgflo-nodejs), since that has the relevant APIs
