### ISSUE TITLE
Removed nodes don't get removed from graph JSON

### ISSUE THREAD

**Issue by bergie** [msgflo/msgflo#124]
When running MsgFlo with auto saving enabled, it doesn't remove nodes from the graph JSON file when they've been removed by a client (Flowhub in this instance)

**Comment by jonnor** [comment]
Might also affect other things than the graph JSON. For instance (re)connecting client in live mode will likely see stale data.

**Comment by bergie** [comment]
I think this is a side effect of #131. Since coordinator sometimes fails to stop a participant, the participant is still running and sending discovery messages (that end up as a node in the graph)

**Comment by jonnor** [comment]
We don't remove participant declarations on stopParticipant, and we don't remove on not-seen-in-a-while - so this bug likely always happens with no relation to #131
