### ISSUE TITLE
Support IIPs

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo#15]
Since IIPs are a network/graph level construct the individual participants should not need to know about it. This raises some challenges. Participants can come and go (crashing, intended stop), and each new instance must receive the IIP(s).
Meaning, it is not enough to send it to a queue shared by all participants in a role...
The FBP graph format also has an order of IIPs. This becomes very hard to preserve when lifetimes of participants vary this much. Probably acceptable to drop this requirement though.

There is some code in Coordinator with some IIP handling, but it should probably move into setup somehow because one might need it during normal execution of a network.
Probably needs to continiously listen for FBP participant changes, and when a new participant is discovered it must (re)-send the IIP.

**Comment by jonnor** [comment]
Now that we have startup templating in, maybe we can/should pass IIPs through the commandline?
 `mycommand --initials #INITIALS`, where INITIALS is a JSON object `{ portA: "iipB", portB: "iipB" }`.
This assumes that order of IIPs does not matter, which ought to be fine?

**Comment by bergie** [comment]
@jonnor NoFlo sends IIPs in order of appearance after all processes have started, but in general I think order doesn't matter. A potential problem is, we'd need to send them to each process of the same role (which can start and shut down arbitrarily). Maybe can be done based on discovery messages?

**Comment by jonnor** [comment]
@bergie I'm proposing passing them via the commandline at process startup.

This will of course not work for changing the graph at runtime, but is much better than nothing.
