### ISSUE TITLE
Support for fbp-spec

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo#18]
https://github.com/flowbased/fbp-spec is a testing tool for FBP-runtimes. It would be great if MsgFlo supported it, so one can test multi-participant systems same way we now test individual FBP participants.

Should primarily require some more work on the FBP runtime protocol implementation in the 'coordinator'.

**Comment by jonnor** [comment]
For a first version, might be reasonable to assume/require that the unit under test is set up by the runtime. That way we don't need to support component instantiation, or connecting nodes, just sending messages in/out. Fixing flowbased/fbp-spec#1 would make it more convenient to use

Now that we have the 'library' concept in MsgFlo, it would be possible to support component instatiation though. Tricky part is that often one wants to run tests against a particular 'live' version (don't setup as part of test) where as test/assertion/fixture components are testing specific.

**Comment by bergie** [comment]
Requires #15

**Comment by jonnor** [comment]
Implemented in a series of commit leading up to eb538d8616c919058577eaf92751358d69db88ef

There are probably some rough edges but these can be ironed out as specific issues.
