### ISSUE TITLE
Can't setup the msgFlo

### ISSUE THREAD

**Issue by mohandass-pat** [msgflo/msgflo#181]
Hi,
I'm trying to setup msgFlo

I'm just following this https://msgflo.org/docs/usage/index.html.

I can setup the participants.

repeater(Repeat) OUT -> IN repeaterdup(Repeat)

In this graph, If I send the message repeater participant receives the message. But repeaterdup is not receiving the message.

msgflo-send-message --queue repeater.IN --json '{ "foo": "bar" }'  -- this command sends message to repeater participant.
The second participant is not getting message at all.
 please help me to solve this.
Thanks in advance :)

**Comment by jonnor** [comment]
What broker are you using? What operating system? 
What is the output of the second participant if running with envvar DEBUG=msgflo*
?

**Comment by mohandass-pat** [comment]
I'm using ubuntu 18.04. Trying to setup the same demo from here https://msgflo.org/docs/usage/index.html.

while running with debug I'm getting like this

`  msgflo:mqtt published fbp undefined undefined +0ms
  msgflo:participant registered null +1ms
repeater connected to mqtt://localhost
  msgflo:mqtt message 1 true +9s
  msgflo:participant got msg from queue repeater.IN +9s
+++++ { foo: 'bar' }
  msgflo:mqtt publishing repeater.OUT {"foo":"bar"} +3ms
  msgflo:mqtt published repeater.OUT undefined undefined +0ms
  msgflo:participant register +18s
  msgflo:mqtt publishing fbp {"protocol":"discovery","command":"participant","payload":{"component":"Repeat","icon":"file-word-o","label":"Repeats in data without changes","inports":[{"id":"in","type":"any","hidden":false,"queue":"repeater.IN"}],"outports":[{"id":"out","type":"any","hidden":false,"queue":"repeater.OUT"}],"role":"repeater","id":"repeater-c3bd010c-f31e-4980-9306-0b8a216cef36"}} +18s
  msgflo:mqtt published fbp undefined undefined +1ms
  msgflo:participant registered null +1ms
  msgflo:participant register +27s`

and 

`$ msgflo-setup ./myservice.fbp
Set up participants []
  msgflo:mqtt connected +0ms
  msgflo:routing Binder.addBinding pubsub repeater.OUT-repeateragain.IN +0ms
  msgflo:mqtt subscribing repeater.OUT +2ms
  msgflo:mqtt subscribed repeater.OUT null +1ms
Set up bindings:
 PUBSUB:         repeater.OUT -> repeateragain.IN`

**Comment by mohandass-pat** [comment]
msgflo-setup needs to be run with forever.
