### ISSUE TITLE
FBP participant declarations for foreign nodes

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo#2]
In order to facilitate use of foreign MQTT nodes (and similar systems) which don't have native support for the msgflo FBP discovery messages, the Coordinator should  support providing the FBP participant declarations on behalf of nodes.

The definitions would basically be same as for `msgflo.Participant`, but would contain a matching rule containing a queue/topic. It should be possible to write these as YAML/json, and specify a group of them at once.

The Coordinator (using a helper?) will then listen for data on topics, check against registered rules, and emit the corresponding FBP participant declaration on matches. Since most MQTT nodes send updates periodically, should work pretty well.

**Comment by jonnor** [comment]
One situation we might need this for is https://github.com/c-base/ingress-table/issues/30

**Comment by jonnor** [comment]
This would essentially make the msgflo Coordinator a source of discovery and introspection data on a MQTT network. Interesting also outside wanting to use msgflo/Flowhub to build systems, because stock MQTT does not provide such features.

**Comment by jonnor** [comment]
It should probably be possible to use this tool for a single participant, such that it can be used with the `library` concept in MsgFlo.

**Comment by jonnor** [comment]
A related idea that came up discussing this, would be to generate human-friendly documentation from this structured information, possibly for use by non-FBP systems. Could either be MsgFlo specific, or potentially be done on the FBP level (would maybe allow reuse with NoFlo/MicroFlo). Related to the idea of 'datasheets' for FBP components.

**Comment by bergie** [comment]
Technically these variant declarations (with basic FBP library -style info like descriptions and ports) could also be useful for things like:

* MicroFlo component metadata: https://github.com/microflo/microflo-core/blob/master/components/BoolToInt.hpp#L2
* FBP component manifest noflo/noflo#247

So probably should be standardized and provided with a linter.

Theoretically we could use this also for rudimentary coverage reporting in [fbp-spec](https://github.com/flowbased/fbp-spec) to know what ports are never exercised in any of the tests.

**Comment by bergie** [comment]
Declarations format now exists, [see examples](https://github.com/c-base/c-flo/tree/master/participants)

The `msgflo-register-foreign` tool provides a way to register these to the coordinator. Example:

```
./node_modules/.bin/msgflo-register-foreign participants/c-beam.yml
```
