### ISSUE TITLE
Participants should send discovery messages periodically

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo#30]
Allows to use these messages as a keep-alive signal.

* [x] msgflo-python
* [x] msgflo-nodejs
* [x] msgflo-register-foreign
* [x] msgflo-arduino
* [x] [noflo-runtime-msgflo](https://github.com/noflo/noflo-runtime-msgflo/pull/178)
* [x] [microflo](https://github.com/microflo/microflo/pull/119)
* [x] [msgflo-cpp](https://github.com/msgflo/msgflo-cpp/issues/11)
* [ ] [msgflo-rust](https://github.com/msgflo/msgflo-rust/issues/4)

**Comment by bergie** [comment]
Conceptually similar to the `ping` messages runtimes can send to Flowhub API

**Comment by jonnor** [comment]
Also applies to `msgflo-register-foreign`

**Comment by jonnor** [comment]
Considering this done, everything except for msgflo-rust, which is experimental, implements this.
