### ISSUE TITLE
Normalize saved graph

### ISSUE THREAD

**Issue by bergie** [msgflo/msgflo#59]
It seems auto-save option doesn't normalize process and edge order, meaning you get non-meaningful graph changes on every run where the order of some processes and some edges changes

**Comment by jonnor** [comment]
Yes, no ordering imposed. Pull request welcomed.

What would be a sane ordering? By alphabetically by process name for `processes`, and alphabetically by `${tgt.process}.#{tgt.port}` for connections?

**Comment by jonnor** [comment]
Diffing a graph as .json plain-text is never gonna be super nice though, which is why I started https://github.com/flowbased/fbp-diff

**Comment by bergie** [comment]
@jonnor yes, but still nicer if there are no non-meaningful changes
