### ISSUE TITLE
Tools for emptying and filling queues

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo#6]
Useful when migrating (changing queue names etc), or debugging (creating fixtures from failing data)

    msgflo-dump
    msgflo-fill

**Comment by bergie** [comment]
`msgflo-dump-message` [exists now](https://github.com/the-grid/msgflo/blob/master/bin/msgflo-dump-message)

**Comment by jonnor** [comment]
`msgflo-send-message` [exists now](https://github.com/msgflo/msgflo/blob/master/bin/msgflo-send-message)
