### ISSUE TITLE
Some edges are not connected when opening in live mode

### ISSUE THREAD

**Issue by bergie** [msgflo/msgflo#61]
Original FBP graph definition:

```
ingress-table(c-flo/ingress-table) CBASE -> STATE partymods(c-flo/DetectPartyMods)
partymods LIGHTS -> COLORS ampel-nerd(c-flo/ampel-nerd)
```

However, when opening in Flowhub live mode, these edges are not shown connected:

![screenshot 2017-01-26 at 13 00 01](https://cloud.githubusercontent.com/assets/3346/22330603/614a7d52-e3c7-11e6-82a9-25e4c3b903c6.png)

The only difference between these and other edges seems to be that this particular flow includes a noflo-runtime-msgflo participant

**Comment by bergie** [comment]
One potential reason is that this participant starts quite a bit later than the others

**Comment by jonnor** [comment]
There is a 10-second timeout for waiting for participants. Could try to increase that to see if it helps? It should probably be made configurable.

The related problem is that the coordinator does not ensure that bindings exists for participants which appear at an arbitrary time, outside of the coordinators control...
The challenge here is that we actually have two graphs/networks. One is the *desired* configuration, potentially initially from --graph foo.json, then modified onwards via the FBP protocol client. The other is the *actual* live-situation, which is influenced by participant existance. *Mostly* the coordinator works to adjust the actual situation to match desired, but there are also cases where actual info informs desired - like when unknown participants pop up, or when one port sends directly to another (effectively already bound).

**Comment by jonnor** [comment]
Maybe the cleanest way to represent this would be to keep a list of "pending" actions (needed to realize desired state), with data about any (missing) dependencies attached. Actions without dependencies can be fired right away, but should the list include them? Their realization could fail (and need retrying), so mostly a question of whether we pop optimistically or upon verification of having reached desired state.
On participant changes we'd check our list of pending actions if any dependencies are now met, and if so, execute the action.

**Comment by bergie** [comment]
I'm at least not seeing us hit https://github.com/msgflo/msgflo/blob/master/src/coordinator.coffee#L33

**Comment by bergie** [comment]
Suggestion on how to improve coordinator start-up:
- Start using [fbp-graph](https://www.npmjs.com/package/fbp-graph) as the internal graph representation for better metadata, events, etc
- Load graph from file, mark everything "dead" via node/edge metadata
- When discovery message(s) arrive, rectify graph data and mark affected parts as "non-dead"

**Comment by jonnor** [comment]
Those are all nice-to-have, outside of the scope of this bug.

**Comment by jonnor** [comment]
I investigated this a bit. We are monitoring for participant changes at any time, but our checking/ensuring that queues are setup is broken (`checkParticipantConnections`). 

There are several different cases the code needs to handle.
1) Two (or more) participant in+out ports have the same queue.
That means they are already connected, so we don't need (and should not try) to bind them.
Should ensure that `@connections` contains this fact.
2) Graph says that outport of one participant role should be bound to the inport of another participant role (different queues). If the binding does not exist, have to create it. On success, should update `@connections` with fact that they are now created.

It looks like 2) is broken and this is causing this bug. We actually don't even keep the desired graph or connections around... Need to do that somehow.

**Comment by jonnor** [comment]
Actually the issue was that we were not using the regular codepaths for starting participants / adding connections at all, but using some outdated special-cased-and-generally-broken logic.

**Comment by jonnor** [comment]
![msgflo-connect-startup](https://cloud.githubusercontent.com/assets/45185/23950341/f6239c40-098a-11e7-9519-818a24dee487.png)
