### ISSUE TITLE
Send new component messages only when a component actually changes

### ISSUE THREAD

**Issue by bergie** [msgflo/msgflo#83]
Now it seems that the coordinator sends a `component` message to FBP Protocol subscribers every time it receives a discovery message. This causes constant _Loading_ messages in Flowhub:

![screenshot 2017-02-08 at 19 43 08](https://cloud.githubusercontent.com/assets/3346/22751999/1903907c-ee37-11e6-9e10-dfb725edfcc8.png)

It would be better to send these messages only when the component information _actually_ changes (new ports, whatever), not every ping from participant.

**Comment by jonnor** [comment]
@bergie the last seen information does change every ping.

**Comment by jonnor** [comment]
Hm, I guess that information should be transmitted on the node (not component), so this issue is valid.

**Comment by bergie** [comment]
Component _should be_ sent if the signature changes, though
